openapi: 3.0.3
info:
  version: v1
  title: OpenSearch Dashboards Saved Objects API
  contact:
    name: OpenSearch Dashboards Team
  description: |-
    OpenAPI schema for OpenSearch Dashboards Saved Objects API
tags:
  - name: saved objects
    description: Manage Dashboards saved objects, including dashboards, visualizations, saved search, and more.
paths:
  /api/saved_objects/{type}/{id}:
    get:
      tags:
        - saved objects
      summary: retrieve a single saved object by type and id.
      parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/type'
      responses:
        '200':
          description: The saved object is successfully retrieved. 
          content:
            application/json:
              schema:
                type: object
        '404':
          description: The saved object does not exist.
          content:
            application/json:
              schema:
                type: object
    post:
      tags:
        - saved objects
      summary: Create a saved object
      parameters:
        - $ref: '#components/parameters/type'
        - in: path
          name: id
          required: false
          name: id
          description: Unique id of the saved object.
          schema:
            type: string
        - in: query
          name: overwrite
          description: If set to true, will overwrite the existing saved object with same type and id.
          schema: 
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - attributes
              properties:
                attributes:
                  type: object
                migrationVersion:
                  type: object
                references:
                  type: array
                initialNamespaces:
                  type: array
                workspaces:
                  type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
components:
  parameters:
    type:
      name: type
      in: path
      description: The type of SavedObject to retrieve
      required: true
      schema:
        type: string
    id: 
      name: id
      in: path
      description: Unique id of the saved object.
      required: true
      schema:
        type: string
