openapi: 3.0.3
info:
  version: v1
  title: Saved Object API
  description: |-

    An API for saved objects.

  contact:
    name: Lu Yu
    email: yulu.nju@gmail.com

  license:
    url: https://www.apache.org/licenses/LICENSE-2.0
    name: Apache 2.0

tags:
  - name: Saved Objects
    description: They are dashboards, visualizations, etc

paths:
  /{type}/{id}:
    get:
      tags:
      - Saved Objects
      description: Get a saved object based on type and id
      parameters:
      - name: type
        in: path
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                type: objetc
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  attributes:
                    type: object

    post:
      tags:
      - Saved Objects
      description: Create a saved object
      parameters:
      - name: type
        in: path
        schema:
          type: string
      - name: id
        in: path
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                attributes:
                  type: object
                migrationVersion:
                  type: object
                references:
                  type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object

  /_bulk_create:
    post:
      tags:
      - Saved Object
      description: Bulk create saved objects
      parameters:
      - name: overwrite
        in: query
        schema:
          type: boolean
          description: overwrite existing
          example: true
      - name: workspaces: 
        in: query
        schema: 
          type: array
          description: list of string
          example: []
      requestBody:
        description: Array of saved objects to create
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: 1234
                  type:
                    type: string
                    example: data-source
                  attributes:
                    type: object
                  version:
                    type: string
                  migrationVersion:
                    type: object
                  references:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        name:
                          type: string
                  initialNamespaces:
                    type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array

  