openapi: 3.0.3
info:
  version: v1
  title: OpenSearch Dashboards Saved Objects API
  contact:
    name: OpenSearch Dashboards Team
  description: |-
    OpenAPI schema for OpenSearch Dashboards Saved Objects API
tags:
  - name: saved objects
    description: Manage Dashboards saved objects, including dashboards, visualizations, saved search, and more.
paths:
  /api/saved_objects/{type}/{id}:
    get:
      tags:
        - saved objects
      summary: retrieve a single saved object by type and id.
      parameters:
      - $ref: '#/components/parameters/id'
      - $ref: '#/components/parameters/type'
      responses:
        '200':
          description: The saved object is successfully retrieved. 
          content:
            application/json:
              schema:
                type: object
        '404':
          description: The saved object does not exist.
          content:
            application/json:
              schema:
                type: object
    post:
      tags:
        - saved objects
      summary: Create a saved object
      parameters:
        - $ref: '#components/parameters/type'
        - in: path
          name: id
          required: false
          name: id
          description: Unique id of the saved object.
          schema:
            type: string
        - in: query
          name: overwrite
          description: If set to true, will overwrite the existing saved object with same type and id.
          schema: 
            type: boolean
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - attributes
              properties:
                attributes:
                  type: object
                migrationVersion:
                  type: object
                references:
                  type: array
                initialNamespaces:
                  type: array
                workspaces:
                  type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object

  /api/saved_objects/_bulk_create:
    post:
      tags:
      - Saved Objects
      description: Bulk create saved objects
      parameters:
      - name: overwrite
        in: query
        schema:
          type: boolean
          description: overwrite existing
          example: true
      - name: workspaces
        in: query
        schema: 
          type: array
          description: list of string
          example: []
      requestBody:
        description: Array of saved objects to create
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    example: 1234
                  type:
                    type: string
                    example: data-source
                  attributes:
                    type: object
                  version:
                    type: string
                  migrationVersion:
                    type: object
                  references:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        name:
                          type: string
                  initialNamespaces:
                    type: array
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: array
  /api/saved_objects/_export:
    post:
      summary:
      tags:
        - saved objects
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                type:
                  description: Type of saved objects to include in the export
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                objects:
                  description: List of saved objects to export.
                  type: array
                  items:
                    type: object
                search:
                  type: string
                includeReferencesDeep:
                  type: boolean
                  default: false
                  description: Includes all of the referenced objects in the exported objects.
                excludeExportDetails:
                  type: boolean
                  default: false
                  description:
                workspaces: 
                  type: array
                  items:
                    type: string
                  description: List of workspaces TODO: add details
      responses:
        '200':
          description: Export is successful
          content:
            application/ndjson:
              schema:
                type: object
                additionalProperties: true
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400_bad_request'
  /api/saved_objects/_import:
    post:
      summary: 
      tags:
        - saved objects
      parameters:
        - in: query
          name: overwrite
          schema:
            type: boolean
          required: false
          description: If true, will overwrite saved object if already exists
        - in: query
          name: createNewCopies
          schema:
            type: boolean
          required: false
          description: If true, will create new id for the saved objects
        - in: query
          name: dataSourceId
          schema:
            type: string
          required: false
          description: If specified, will use the data source id as reference for the index pattern TODO: add details
        - in: query
          name: dataSourceEnabled
          schema:
            type: boolean
          required: false
        - in: query
          name: workspaces
          schema:
            oneOf:
              - type: string
              - type: array
                items:
                  type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: The ndjson or json file which contains the saved objects to be imported.
      responses:
        '200':
          description: Import is successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: All saved objects in the file have been successfully imported.
                  successCount:
                    type: integer
                    description: Number of successfully imported saved objects.
                  successResults:
                    type: array
                    items:
                      type: object
                    description: List which contains the metadata of successfully imported saved objects if applicable.
                  errors:
                    type: array
                    items:
                      type: object
                    description: List which contains the metadata of saved objects which failed to be imported. 
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/400_bad_request'
  /api/saved_objects/_resolve_import_errors:
    post:
      summary: Triggers logic to resolve errors by retrying failed import actions
      tags:
        - saved objects
      parameters:
        - in: query
          name: createNewCopies
          schema:
            type: boolean
          required: false
          description: Create new copies of the saved objects by generating new id
        - in: query
          name: dataSourceId
          schema:
            type: string
          required: false
          description: Id of the data source TODO add detail
        - in: query
          name: workspaces
          schema:
            type: array
            items:
              type: string
          required: false
          description: TODO add detail
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - retries
              properties:
                file: 
                  description: TODO
                  type: string
                  format: binary
                retries:
                  description: TODO
                  type: array
                  items:
                    type: object
                    required:
                      - type
                      - id
                    properties:
                      type:
                        description: 
                        type: string
                        

                  
components:
  parameters:
    type:
      name: type
      in: path
      description: The type of SavedObject to retrieve
      required: true
      schema:
        type: string
    id: 
      name: id
      in: path
      description: Unique id of the saved object.
      required: true
      schema:
        type: string
  schemas:
    400_bad_request:
      title: Bad request
      type: object
      required:
        - error
        - message
        - statusCode
      properties:
        error:
          type: string
          enum:
            - Bad Request
        message:
          type: string
        statusCode:
          type: integer
          enum:
            - 400
